name: 'Add issue comment (js)'
description: 'Adiciona comentário em uma issue'
author: 'Fabricio Veronez'
inputs:
  GITHUB_TOKEN:
    description: 'Token do GitHub'
    required: true
  issue-id:
    description: 'ID da issue que deve ser comentada'
    required: true
  comment:
    description: 'Comentário que deve ser adicionando na issue'
    required: true
outputs:
  comment-id:
    description: 'ID do comentário criado'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'archive'
  color: 'gray-dark'