on: 
    issues: 
        types: [opened]
    pull_request:
        types: [opened]
jobs:
  test-action-job:
    runs-on: ubuntu-latest
    name: Teste da Action de Comentário
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - name: Executando a Action
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          issue-id: ${{ github.event.issue.number }}
          comment: 'Teste de comentário'
      # Use the output from the `hello` step
      #- name: Get the output time
      #  run: echo "The time was ${{ steps.hello.outputs.time }}"
